services:
  app:
    image: samzyre/riveting-bot
    container_name: riveting-bot
    env_file: .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN:?discord token not set}
    volumes:
      - ./data:/data
    build:
      context: .
      dockerfile: ./Dockerfile
      # args:
      #   - BOT_PROFILE=dev
      #   - BOT_TARGET=debug
