
unstable_features = true

# Ordering
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true
use_field_init_shorthand = true

# Extra
format_macro_matchers = true
format_strings = true
overflow_delimited_expr = true
