
unstable_features = true

# Ordering
group_imports = "StdExternalCrate"
imports_granularity = "Module"
reorder_impl_items = true

# Reformat
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true

# Extra
format_macro_matchers = true
format_strings = true
match_block_trailing_comma = true
